An A/B test was set into motion from 3/15/2017 to 6/20/2017 by the team.

Control Group: Clients interacted with Vanguard's traditional online process.
Test Group: Clients experienced the new, spruced-up digital interface.
Both groups navigated through an identical process sequence: an initial page, three subsequent steps, and finally, a confirmation page signaling process completion.

The goal is to see if the new design leads to a better user experience and higher process completion rates.

This Notebook focus on data cleaning and organisation for later analysis

First, we import libraries and tell jupyter the path of source files.

In [16]:
import pandas as pd
import pandas as pd
import yaml

In [17]:
#function to read raw data with the yaml file configuration
def read_file(yaml_path, inp_data_section, file_name):
    try:
        with open(yaml_path, "r") as file:
            cfg = yaml.safe_load(file)
    except:
        print("Yaml configuration file not found!")
        return None

    raw_df = pd.read_csv(cfg[inp_data_section][file_name])  # ✅
    return raw_df

In [18]:
yaml_path= "../config.yaml"
inp_data_section = 'input_data'
file_name= 'file3'

#reading the file 3 configured in yaml file as file3: "../data/raw/df_final_experiment_clients.txt"
file3= read_file(yaml_path,inp_data_section,file_name)
f3=file3.copy()
f3.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [5]:
display(f3.info())
print('____')
display(f3.isnull().sum())
f3.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  50500 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.1 MB

None

____

client_id        0
Variation    20109
dtype: int64

np.int64(0)

There are 20109 clients which were not part of the grand experiment. Then, we keep only those who were part of the experiment.

In [6]:
#data frame containint only those client_ids which were part of the experiment, either in Test group or Control group
#fexp=f3.dropna() 
fexp=f3
fexp.info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  50500 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.1 MB

Now we import the Digital Footprints (df_final_web_data) which has a detailed trace of client interactions online, divided into two parts.

In [10]:
#importing the two files
file_name= 'file2p1'
file2p1= read_file(yaml_path,inp_data_section,file_name)

file_name2= 'file2p2'
file2p2= read_file(yaml_path,inp_data_section,file_name2)

In [11]:
#importing the two files

f2p1=file2p1.copy() #file part 1
f2p2=file2p2.copy() #file part 2

In [12]:
f2p1.info()
print('____________')
f2p2.info()

<class 'pandas.DataFrame'>
RangeIndex: 343141 entries, 0 to 343140
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     343141 non-null  int64
 1   visitor_id    343141 non-null  str
 2   visit_id      343141 non-null  str
 3   process_step  343141 non-null  str
 4   date_time     343141 non-null  str
dtypes: int64(1), str(4)
memory usage: 13.1 MB
____________
<class 'pandas.DataFrame'>
RangeIndex: 412264 entries, 0 to 412263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     412264 non-null  int64
 1   visitor_id    412264 non-null  str
 2   visit_id      412264 non-null  str
 3   process_step  412264 non-null  str
 4   date_time     412264 non-null  str
dtypes: int64(1), str(4)
memory usage: 15.7 MB

In [13]:
display(f2p1.head(1))
display(f2p2.head(1))

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00

In [14]:
#We check if there are duplicated rows
display(f2p1.duplicated().sum())
f2p1[f2p1.duplicated(keep=False)].head(4)  # shows ALL copies, not just 2nd occurrence

np.int64(2095)

,client_id,visitor_id,visit_id,process_step,date_time
364,9358626,148475529_63668223960,223297395_36250329195_832161,start,2017-04-28 12:27:28
365,9358626,148475529_63668223960,223297395_36250329195_832161,start,2017-04-28 12:27:28
367,5376894,622509328_44408201172,688984457_43441834354_912755,start,2017-04-28 14:20:01
368,5376894,622509328_44408201172,688984457_43441834354_912755,start,2017-04-28 14:20:01

In [15]:
f2p1=f2p1.drop_duplicates()
f2p1.shape

(341046, 5)

In [16]:
#We check if there are duplicated rows for the second data set
display(f2p2.duplicated().sum())
f2p2[f2p2.duplicated(keep=False)].head(4)  # shows ALL copies, not just 2nd occurrence

np.int64(8669)

,client_id,visitor_id,visit_id,process_step,date_time
124,3751049,937925261_74821699083,628817270_45049432060_475841,start,2017-05-15 23:09:44
125,3751049,937925261_74821699083,628817270_45049432060_475841,start,2017-05-15 23:09:44
142,9912156,746623513_52101087617,780044921_57678038107_984942,start,2017-05-03 14:09:52
143,9912156,746623513_52101087617,780044921_57678038107_984942,start,2017-05-03 14:09:52

In [17]:
f2p2=f2p2.drop_duplicates()
f2p2.shape

(403595, 5)

As the two data frames have same column names, structure, dtypes and no-null data, we concatenate vertically

In [18]:
# Concatenating files vertically (along rows)
f2=pd.concat([f2p1, f2p2], axis=0).reset_index(drop=True)
display(f2.info())
display(f2.head(2))

<class 'pandas.DataFrame'>
RangeIndex: 744641 entries, 0 to 744640
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     744641 non-null  int64
 1   visitor_id    744641 non-null  str
 2   visit_id      744641 non-null  str
 3   process_step  744641 non-null  str
 4   date_time     744641 non-null  str
dtypes: int64(1), str(4)
memory usage: 28.4 MB

None

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51

In [19]:
# Merge the sales and revenue DataFrames on the 'Date' column (inner join)
# Only rows with a common value in the 'client_id' column, present in both DataFrames, are included in the merged result.
df=pd.merge(fexp, f2, on='client_id')
display(df.info())
display(df.head(2))

<class 'pandas.DataFrame'>
RangeIndex: 443897 entries, 0 to 443896
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     443897 non-null  int64
 1   Variation     317235 non-null  str
 2   visitor_id    443897 non-null  str
 3   visit_id      443897 non-null  str
 4   process_step  443897 non-null  str
 5   date_time     443897 non-null  str
dtypes: int64(1), str(5)
memory usage: 20.3 MB

None

,client_id,Variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51

In [20]:
df[df.Variation.isnull()].head(5)

,client_id,Variation,visitor_id,visit_id,process_step,date_time
317235,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,confirm,2017-05-22 12:14:45
317236,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_3,2017-05-22 12:14:27
317237,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_2,2017-05-22 12:14:13
317238,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_1,2017-05-22 12:13:50
317239,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,start,2017-05-22 12:13:43

In [21]:
df[df['client_id'] == 5459747]

,client_id,Variation,visitor_id,visit_id,process_step,date_time
317235,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,confirm,2017-05-22 12:14:45
317236,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_3,2017-05-22 12:14:27
317237,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_2,2017-05-22 12:14:13
317238,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,step_1,2017-05-22 12:13:50
317239,5459747,NaN,927506343_21566395546,126601512_42206463738_739012,start,2017-05-22 12:13:43

In [22]:
df.duplicated().sum()

np.int64(0)

We leave the rows with the NaN in the variation column in case it could be useful to see this client_id later

Now, this data set is ready for analysis, we create the ready file to csv:

In [27]:
def out_csv(df,yaml_path,output_section_yaml,file_name):
    try:
        with open(yaml_path, "r") as file:
            cfg = yaml.safe_load(file)
    except:
        print("Yaml configuration file not found!")
        return None
        
    df.to_csv(cfg[output_section_yaml][file_name], index=False)
    print(f"File saved to: {cfg[output_section_yaml][file_name]}")

In [28]:
#exporting csv to the clean data folder as specified with the yaml file:   file2: "../data/clean/digfootpring_groups_clean.csv"

yaml_path= "../config.yaml"
output_section_yaml='output_data'
out_file_name= 'file2'    

out_csv(df,yaml_path,output_section_yaml,out_file_name)

File saved to: ../data/clean/digfootpring_groups_clean.csv