In [1]:
#Mergin datasets
import pandas as pd
import pandas as pd
import yaml

#function to read raw data with the yaml file configuration
def read_file(yaml_path, inp_data_section, file_name):
    try:
        with open(yaml_path, "r") as file:
            cfg = yaml.safe_load(file)
    except:
        print("Yaml configuration file not found!")
        return None

    raw_df = pd.read_csv(cfg[inp_data_section][file_name])  # ✅
    return raw_df

In [2]:
yaml_path= "../config.yaml"
inp_data_section = 'output_data'
f1= 'file1' #clean_final_demo.csv
f2='file2' #digfootpring_groups.csv

In [3]:
#importing the two files

f1= read_file(yaml_path,inp_data_section,f1)
f2= read_file(yaml_path,inp_data_section,f2)

display(f1.head(1))
display(f2.head(1))

/var/folders/y7/p6n8z7nn4fs88vn9n57nxbh40000gn/T/ipykernel_13808/3554826707.py:15: DtypeWarning: Columns (0: Variation) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv(cfg[inp_data_section][file_name])  # ✅

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0

,client_id,Variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07

In [4]:
f1.info()
print('________')
f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 70595 entries, 0 to 70594
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70595 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70595 non-null  float64
 4   gendr             70595 non-null  str
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 4.8 MB
________
<class 'pandas.DataFrame'>
RangeIndex: 443897 entries, 0 to 443896
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     443897 non-null  int64
 1   Variation     317235 non-null  str
 2   visitor_id    443897 non-null  str
 3   visit_id      443897 non-null  str
 4   process_step  443897 non-null  str
 5   date_time     443897 non-null  str
dtypes: int64(1), str(5)
memory usage: 20.3 MB

In [5]:
merged_df = pd.merge(f1, f2, on='client_id', how='outer')
display(merged_df.head(2))
print('__________')
merged_df.info()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation,visitor_id,visit_id,process_step,date_time
0,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,NaN,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
1,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,NaN,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05

__________
<class 'pandas.DataFrame'>
RangeIndex: 443897 entries, 0 to 443896
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   client_id         443897 non-null  int64
 1   clnt_tenure_yr    443784 non-null  float64
 2   clnt_tenure_mnth  443784 non-null  float64
 3   clnt_age          443784 non-null  float64
 4   gendr             443784 non-null  str
 5   num_accts         443784 non-null  float64
 6   bal               443784 non-null  float64
 7   calls_6_mnth      443784 non-null  float64
 8   logons_6_mnth     443784 non-null  float64
 9   Variation         317235 non-null  str
 10  visitor_id        443897 non-null  str
 11  visit_id          443897 non-null  str
 12  process_step      443897 non-null  str
 13  date_time         443897 non-null  str
dtypes: float64(7), int64(1), str(6)
memory usage: 47.4 MB